name: Package Application with Pyinstaller

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: Commercial_Tool_src

    - uses: actions/upload-artifact@v4
      with:
        name: Commercial_Tool.exe
        path: Commercial_Tool_src/dist/windows

  create-release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v4
      with:
        path: ./

    - name: Create github release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release Version ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload windows artifact to github release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Commercial_Tool.exe
        asset_name: Commercial_Tool.exe
        asset_content_type: application
      