name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: Commercial_Tool_src

    - uses: actions/upload-artifact@v2
      with:
        name: Commercial_Tool.zip
        path: Commercial_Tool_src/dist/windows

    - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Commercial_Tool_src/dist/windows/Commercial_Tool.exe
