name: Package Application with Pyinstaller

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: Commercial_Tool_src

    - uses: actions/upload-artifact@v4
      with:
        name: Commercial_Tool
        path: Commercial_Tool_src/dist/windows

  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    needs: build

    steps:
      - name: "Build & test"
        run: echo "done!"
        
      - uses: actions/download-artifact@v4
        with:
          path: ./

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: ./Commercial_Tool